import puppeteer from 'puppeteer-core';
import { mkdtempSync } from 'node:fs';
const [, , route, sel, out, idx = '1'] = process.argv;
const b = await puppeteer.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: 'new', userDataDir: mkdtempSync(process.env.TEMP + '/pp-') });
const p = await b.newPage();
await p.setViewport({ width: 1440, height: 900 });
const errs = [];
p.on('pageerror', (e) => errs.push(e.message));
await p.goto('http://localhost:4327' + route, { waitUntil: 'networkidle2' });
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
await p.evaluate((s) => document.querySelector(s).scrollIntoView({ block: 'center' }), sel);
await sleep(2500);
await p.screenshot({ path: out + '-rest.jpg', type: 'jpeg', quality: 70 });
const box = await p.evaluate((s, i) => { const r = document.querySelectorAll(s)[i].getBoundingClientRect(); return { x: r.x, y: r.y, w: r.width, h: r.height }; }, sel + ' .gcard, ' + sel, +idx).catch(() => null);
const r = await p.evaluate((s) => { const e = document.querySelectorAll(s + ' .tilt')[1] || document.querySelector(s + ' .tilt'); const q = e.getBoundingClientRect(); return { x: q.x, y: q.y, w: q.width, h: q.height }; }, sel);
await p.mouse.move(r.x + r.w * 0.5, r.y + r.h * 0.5); await sleep(300);
await p.mouse.move(r.x + r.w * 0.8, r.y + r.h * 0.25, { steps: 8 }); await sleep(800);
await p.screenshot({ path: out + '-hover.jpg', type: 'jpeg', quality: 70 });
console.log(JSON.stringify({ errs, tilt: await p.evaluate((s) => getComputedStyle(document.querySelectorAll(s + ' .tilt')[1] || document.querySelector(s + ' .tilt')).transform, sel) }));
await b.close();
